### ISSUE TITLE
Allow placeholders in tag fallback configuration

### ISSUE THREAD

**Issue by Silthus** [AlonsoAliaga/AlonsoTags#1]
**Is your feature request related to a problem? Please describe.**
I have some prefixes for groups in LuckPerms configured and want to use those as a fallback when no tag is selected.

**Describe the solution you'd like**
Allow using placeholders in the `None: ''` part of the config for fallback tags.

```yaml
    Tag-chat:
      # allow using placeholders here (and maybe in the other parts too?)
      None: "{vault_prefix}"
      Format: "{TAG} "
```
